name: docker-react-ci
on:
  push:
    branches:
      - main

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build docker image with dev Dockerfile 
        run: docker build -t docker-react -f Dockerfile.dev .

      - name: Run npm tests
        run: docker run -e CI=true docker-react npm run test